"""
SMTP email sender for deal summaries.

Supports both STARTTLS (port 587) and SSL/TLS (port 465) connections.
All credentials are read from environment variables.
"""
import os
import smtplib
import ssl
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import List, Optional


class EmailSendError(Exception):
    """Raised when the email cannot be sent."""


def _build_html_email(
    summary_html: str,
    filenames: List[str],
    company_hint: str = "",
) -> str:
    """Wrap the summary table in a full HTML email body."""
    file_list = "".join(f"<li>{fn}</li>" for fn in filenames)
    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    subject_line = f"Deal Summary{': ' + company_hint if company_hint else ''}"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {{
      font-family: Arial, sans-serif;
      color: #1a202c;
      background: #f7fafc;
      margin: 0;
      padding: 20px;
    }}
    .container {{
      max-width: 900px;
      margin: 0 auto;
      background: #ffffff;
      border-radius: 8px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.08);
      overflow: hidden;
    }}
    .header {{
      background: #1a365d;
      color: #ffffff;
      padding: 24px 32px;
    }}
    .header h1 {{
      margin: 0 0 4px;
      font-size: 22px;
      font-weight: 700;
    }}
    .header p {{
      margin: 0;
      font-size: 13px;
      opacity: 0.75;
    }}
    .body {{
      padding: 28px 32px;
    }}
    .meta {{
      background: #ebf4ff;
      border-left: 4px solid #3182ce;
      padding: 12px 16px;
      margin-bottom: 24px;
      border-radius: 0 4px 4px 0;
    }}
    .meta p {{
      margin: 0 0 4px;
      font-size: 13px;
      color: #2b6cb0;
    }}
    .meta ul {{
      margin: 6px 0 0;
      padding-left: 20px;
      font-size: 13px;
      color: #2b6cb0;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 14px;
    }}
    table th {{
      background: #edf2f7;
      color: #2d3748;
      font-weight: 600;
      text-align: left;
      padding: 10px 14px;
      border: 1px solid #cbd5e0;
      width: 22%;
      vertical-align: top;
    }}
    table td {{
      padding: 10px 14px;
      border: 1px solid #cbd5e0;
      vertical-align: top;
      line-height: 1.5;
    }}
    table tr:nth-child(even) td {{
      background: #f7fafc;
    }}
    .footer {{
      padding: 16px 32px;
      background: #f7fafc;
      border-top: 1px solid #e2e8f0;
      font-size: 12px;
      color: #718096;
      text-align: center;
    }}
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Deal Room Summary</h1>
      <p>Generated {timestamp}</p>
    </div>
    <div class="body">
      <div class="meta">
        <p><strong>Source documents ({len(filenames)} file{'s' if len(filenames) != 1 else ''}):</strong></p>
        <ul>{file_list}</ul>
      </div>
      {summary_html}
    </div>
    <div class="footer">
      Generated by Deal Room Processor &nbsp;&bull;&nbsp; Athletic VC
    </div>
  </div>
</body>
</html>"""


def send_summary(
    summary_html: str,
    filenames: List[str],
    company_hint: str = "",
    recipient: Optional[str] = None,
) -> None:
    """
    Send the deal summary HTML table via SMTP.

    All SMTP settings are read from environment variables:
      SMTP_HOST       — e.g. smtp.gmail.com
      SMTP_PORT       — 587 (STARTTLS) or 465 (SSL)
      SMTP_USERNAME   — your email address / login
      SMTP_PASSWORD   — your password or app-specific password
      SMTP_FROM       — sender address (defaults to SMTP_USERNAME)
      EMAIL_RECIPIENT — recipient address (defaults to will@athletic.vc)

    Raises EmailSendError on any failure.
    """
    host = os.environ.get("SMTP_HOST", "").strip()
    port_str = os.environ.get("SMTP_PORT", "587").strip()
    username = os.environ.get("SMTP_USERNAME", "").strip()
    password = os.environ.get("SMTP_PASSWORD", "").strip()
    from_addr = os.environ.get("SMTP_FROM", username).strip()
    to_addr = recipient or os.environ.get("EMAIL_RECIPIENT", "will@athletic.vc").strip()

    # Validate required settings
    missing = [name for name, val in [
        ("SMTP_HOST", host),
        ("SMTP_USERNAME", username),
        ("SMTP_PASSWORD", password),
    ] if not val]
    if missing:
        raise EmailSendError(
            f"Missing required SMTP environment variables: {', '.join(missing)}. "
            "Check your .env file."
        )

    try:
        port = int(port_str)
    except ValueError:
        raise EmailSendError(f"SMTP_PORT must be an integer, got: '{port_str}'")

    subject = f"Deal Room Summary{': ' + company_hint if company_hint else ''}"
    html_body = _build_html_email(summary_html, filenames, company_hint)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    try:
        if port == 465:
            # SSL connection
            context = ssl.create_default_context()
            with smtplib.SMTP_SSL(host, port, context=context, timeout=30) as server:
                server.login(username, password)
                server.sendmail(from_addr, [to_addr], msg.as_string())
        else:
            # STARTTLS connection (port 587 or 25)
            with smtplib.SMTP(host, port, timeout=30) as server:
                server.ehlo()
                server.starttls(context=ssl.create_default_context())
                server.ehlo()
                server.login(username, password)
                server.sendmail(from_addr, [to_addr], msg.as_string())
    except smtplib.SMTPAuthenticationError as exc:
        raise EmailSendError(
            f"SMTP authentication failed for '{username}' on {host}:{port}. "
            "Check your SMTP_USERNAME and SMTP_PASSWORD. "
            "For Gmail you need an App Password (not your regular password)."
        ) from exc
    except smtplib.SMTPConnectError as exc:
        raise EmailSendError(
            f"Could not connect to SMTP server {host}:{port}. "
            "Verify SMTP_HOST and SMTP_PORT."
        ) from exc
    except smtplib.SMTPRecipientsRefused as exc:
        raise EmailSendError(
            f"Recipient address '{to_addr}' was refused by the server."
        ) from exc
    except smtplib.SMTPException as exc:
        raise EmailSendError(f"SMTP error: {exc}") from exc
    except TimeoutError as exc:
        raise EmailSendError(
            f"Connection to {host}:{port} timed out. "
            "Check that your SMTP server is reachable."
        ) from exc
    except OSError as exc:
        raise EmailSendError(
            f"Network error connecting to {host}:{port}: {exc}"
        ) from exc
